// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVplXjSDltcCmjd0UCVsU469uff8-Ysyg',
    appId: '1:548395235432:web:25a6606e572a132db223dd',
    messagingSenderId: '548395235432',
    projectId: 'task-manager-86599',
    authDomain: 'task-manager-86599.firebaseapp.com',
    storageBucket: 'task-manager-86599.appspot.com',
    measurementId: 'G-NPBRHNL0Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQAVQ1-qHoDaoYG7cIWJiL3AXI_rxvmNc',
    appId: '1:548395235432:android:ce3af08b7ba237dfb223dd',
    messagingSenderId: '548395235432',
    projectId: 'task-manager-86599',
    storageBucket: 'task-manager-86599.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANp5NuYi-lPbRKhJyFfBJVP29bAmByh7c',
    appId: '1:548395235432:ios:b0bb6fd891c86312b223dd',
    messagingSenderId: '548395235432',
    projectId: 'task-manager-86599',
    storageBucket: 'task-manager-86599.appspot.com',
    iosClientId: '548395235432-dlpqah4sf5tm8qovlh85m9e8v7e16j7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANp5NuYi-lPbRKhJyFfBJVP29bAmByh7c',
    appId: '1:548395235432:ios:b0bb6fd891c86312b223dd',
    messagingSenderId: '548395235432',
    projectId: 'task-manager-86599',
    storageBucket: 'task-manager-86599.appspot.com',
    iosClientId: '548395235432-dlpqah4sf5tm8qovlh85m9e8v7e16j7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskList',
  );
}
